config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search/index'
  get 'search/result'
  get 'search/treeResult'
  get 'about/index'
  get 'trees/index'
  get 'trees/show'
  get 'parks/index'
  get 'parks/show'

  resources :search, only: [:index] do
    collection do
      get 'result'
    end
  end

  resources :search, only: [:index] do
    collection do
      get 'treeResult'
    end
  end

  resources :parks do
    resources :trees
  end

  resources :trees do
    resources :parks
  end

  root to: 'about#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
# frozen_string_literal: true

class Park < ApplicationRecord
  has_many :trees
  validates :name, :address, :category, presence: true
end

app/models/tree.rb
# frozen_string_literal: true

class Tree < ApplicationRecord
  belongs_to :park
  validates :botanical_name, :common_name, presence: true
  paginates_per 50
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parks_controller.rb
# frozen_string_literal: true

class ParksController < ApplicationController
  def index
    # @parks = Park.includes(:trees).all
    @parks = Park.order(:name).page params[:page]
  end

  def show
    @park = Park.find(params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index; end

  def result
    @parks = Park.where('name LIKE ?', "%#{params[:q]}%").order(:name).page params[:page]
    @park_count = Park.where('name LIKE ?', "%#{params[:q]}%")
  end

  def treeResult
    @trees = Tree.where('botanical_name LIKE ? OR common_name LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%").order(:botanical_name).page params[:page]
    @tree_count = Tree.where('botanical_name LIKE ? OR common_name LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
  end
end

app/controllers/trees_controller.rb
# frozen_string_literal: true

class TreesController < ApplicationController
  def index
    @trees = Tree.order(:botanical_name).page params[:page]
  end

  def show
    @tree = Tree.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/about/index.html.erb
<h1 id="center">About</h1>

<p>I have one Praks table and one Trees table. Park can have more than one trees and a tree belong to only one park.</p>
<%= image_tag("erd.png", alt: "ERD Diagram")%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MidtermProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="arrange">
      <ul class="navbar-nav mr-auto">
        <li class="navbar-brand"><%= link_to 'About Us', about_index_path %></li>
        <li class="navbar-brand"><%= link_to 'Parks', parks_index_path%></li>
        <li class="navbar-brand"><%= link_to 'Trees', trees_index_path %></li>
      </ul>
    </nav>
    </div>
      <%= yield %>
  </body>
</html>

app/views/parks/index.html.erb
<h1 id="center">Parks</h1>

 <div class="paginate">
  <%= paginate @parks, window: 2 %>
 </div>

<%= form_tag(result_search_index_path, method: "get", :class => 'd-inline-block', :id => 'right') do %>
  <%= label_tag(:q, "Search for Parks:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Park Name</th>
        <th>Address</th>
        <th>Park Category</th>
      </tr>
    </thead>
    <% @parks.each do |park| %>
      <tr>
        <td><%=link_to park.name, park_path(park)%></td>
        <td><%=park.address%></td>
        <td><%=park.category%></td>
      </tr>
    <%end%>
  </table>

app/views/parks/show.html.erb
<h1 id="center">Trees in <%=@park.name%> Park</h1>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Botanical Name</th>
        <th>Common Name</th>
      </tr>
    </thead>
    <% @park.trees.each do |tree| %>
      <tr>
        <td><%=link_to tree.botanical_name, tree_path(tree)%></td>
        <td><%=tree.common_name%></td>
      </tr>
    <%end%>
  </table>

app/views/search/index.html.erb
<h1 id="center">Search</h1>

<div class="container">
  <h2> Search Results </h2>

  <%= form_tag(result_search_index_path, method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>

</div>

app/views/search/result.html.erb
<h1 id="center">Search for Parks</h1>
<div class="container">
  <h1> Parks found: <%= @park_count.size %></h1>
  <% if @parks.empty? %>
    <p>Sorry, no parks found.</p>
  <% else %>
    <div class="d-inline-block">
      <%= paginate @parks, window: 2 %>
    </div>
    <%= form_tag(result_search_index_path, method: "get", :class => 'd-inline-block', :id => 'right') do %>
      <%= label_tag(:q, "Search for Park:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Park Name</th>
          <th>Address</th>
          <th>Park Category</th>
        </tr>
      </thead>
      <% @parks.each do |park| %>
        <tr>
          <td><%=link_to park.name, park_path(park)%></td>
          <td><%=park.address%></td>
          <td><%=park.category%></td>
        </tr>
      <%end%>
    </table>
  <% end %>
</div>

app/views/search/treeResult.html.erb
<h1 id="center">Search for Tress</h1>
<div class="container">
  <h1> Trees found: <%= @tree_count.size %></h1>
  <% if @trees.empty? %>
    <p>Sorry, no trees found.</p>
  <% else %>
    <div class="d-inline-block">
      <%= paginate @trees, window: 2 %>
    </div>
    <%= form_tag(treeResult_search_index_path, method: "get", :class => 'd-inline-block', :id => 'right') do %>
      <%= label_tag(:q, "Search for Tree:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
    <% end %>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Botanical Name</th>
          <th>Common Name</th>
        </tr>
      </thead>
      <% @trees.each do |tree| %>
        <tr>
          <td><%=link_to tree.botanical_name, tree_path(tree)%></td>
          <td><%=tree.common_name%></td>
        </tr>
      <%end%>
    </table>
  <% end %>
</div>

app/views/trees/index.html.erb
<h1 id="center">Trees</h1>
<div class="paginate">
    <%= paginate @trees, window: 2 %>
</div>

<%= form_tag(treeResult_search_index_path, method: "get", :class => 'd-inline-block', :id => 'right') do %>
    <%= label_tag(:q, "Search for Trees:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end %>

<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Botanical Name</th>
        <th>Common Name</th>
      </tr>
    </thead>
    <% @trees.each do |tree| %>
      <tr>
        <td><%=link_to tree.botanical_name, tree_path(tree)%></td>
        <td><%=tree.common_name%></td>
      </tr>
    <%end%>
  </table>

app/views/trees/show.html.erb
<h1 id="center"><%=@tree.botanical_name%> is in <%=@tree.park.name%></h1>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Park Name</th>
        <th>Address</th>
        <th>Park Category</th>
      </tr>
    </thead>
      <tr>
        <td><%=link_to @tree.park.name, park_path(@tree.park)%></td>
        <td><%=@tree.park.address%></td>
        <td><%=@tree.park.category%></td>
      </tr>
  </table>
  <% map_url = "https://image.maps.api.here.com/mia/1.6/mapview?app_id=bL1d7bg8QUUxbBqhUe3s&app_code=I5yJwy4TZeC_-x7UvBgSnw&lat=#{@tree.lat}&lon=#{@tree.long}&vt=0&z=11&h=600&w=800"%>
  <%= image_tag(map_url, alt: "tree location") %>